### PR TITLE
Transparency support

### PR DESCRIPTION
**Pull request by w0rm**
Opening this PR for the purpose of discussing the approach and tracking the progress. 

transparency

The compiled example can be seen here: https://unsoundscapes.com/transparency/

- [x] transparent mesh entities are collected in a separate rendering pass using `TransparentMeshNode`
- [x] render first back faces and then front faces of transparent entities
- [x] switch colours to vec4 to accommodate alpha channel
- [x] premultiply all colours with alpha channel in uniforms (colour premultiplication is currently done in uniforms, I was thinking about doing this in material constructors, but this didn't work in `Material.constant`)
- [x] adjust shaders to take alpha from colours and re-attach it when setting `gl_FragColor`
- [x] shadows & transparency — the current implementation is to render transparent objects on top of shadows and opaque objects
- [x] change toSrgb in shaders to work on vec4 and demultiply alpha then multiply back
- [x] a trick to use `float(sign(` as a switch between constant colour and texture colour
- [x] ensure that lights are set to have alpha = 1
- [x] render entities with constant alpha = 0 as `Entity.empty`
- [x] transparency support for non-mesh entities 

Not included in this PR, can be added later:

- [ ] texture support (`loadTransparentWith : String -> Task Error (Texture value)` and `type TextureTransparency = Opaque | Transparent Bool` with premultiplied alpha or non-premultiplied alpha)

### CODE REVIEW

**Comment by ianmackenzie** [comment]
One more thing to think about: how should transparency interact with `Mesh.cullBackFaces`? It might 'just work' as is but I can also imagine it potentially leading to weird artifacts, since I haven't been spent a lot of time on how the insides of faces (triangles pointing away from a light source) get rendered.

**Comment by w0rm** [comment]
@ianmackenzie I looked into that, turns out back facing triangles are rendered the same as front facing.

```
float getNormalSign() {
            return 2.0 * float(gl_FrontFacing) - 1.0;
        }
```

**Comment by frnco** [comment]
I was trying this out and apparently when I draw multiple quads transparency is rendered one-way only. I tried changing the order for the vertices but no matter how I do it I can only get one of the two overlapping quads to have transparency.

One-way-transparency

One-way-transparencyMiddle

I couldn't figure a way to make both faces transparent. there's probably something I'm not getting right but even if it's not a bug, it'd be nice to have at least some documentation on what causes this and how to deal with it.

**Comment by w0rm** [comment]
@frnco this solution only works for a single transparent layer (well, first it renders one layer of back facing polygons and then one layer of front facing polygons). 

Maybe that’s what happens here in case of quads, if the back facing quad is closer to the camera, then it prevents front facing polygons from being rendered because it fills z-buffer. Can you paste the code to reproduce this?

**Comment by frnco** [comment]
Well the actual code I'm working on is quite bad as it's both me learning Elm and an attempt to approach rendering dynamically-generated objects, based on user input, but I tried to clean it up as best as I can and stripped out most of the user input parts (Adding faces, removing faces, as well as changing the angle between faces and length for face profile) while keeping the rendering part mostly intact, or at least as much as was reasonable, and here it is:


```Elm
module Piece exposing (main)

import Array exposing (Array)
import Array.Extra as Array
import Browser
import Html exposing (..)
import Html.Attributes exposing (..)
import Html.Events exposing (onInput)
import LineSegment3d exposing (LineSegment3d)
import Direction3d exposing (Direction3d)
import Vector3d exposing (Vector3d)
import Axis3d exposing (Axis3d)
import Point3d exposing (Point3d)
import Length exposing (Length)
import Angle exposing (Angle)
import Pixels
import Camera3d exposing (Camera3d)
import Scene3d exposing (..)
import Scene3d.Material exposing (..)
import Scene3d.Light exposing (..)
import Illuminance
import Color
import Viewpoint3d exposing (Viewpoint3d)

type alias Segment =
  { angle : Int
  , length : Float }

type alias Model =
  { width : Float
  , segments : Array Segment }

init : Model
init =
  { width=10, segments=(Array.fromList [{angle=0, length=3.2},{angle=10, length=3}, {angle=-10, length=5}, {angle=20, length=5}, {angle=-20, length=5}]) }

main =
  Browser.sandbox { init = init, update = update, view = view }

type Msg
  = SetWidth String

update : Msg -> Model -> Model
update msg model =
  case msg of
    SetWidth pieceWidth ->
      { model | width = (Maybe.withDefault model.width (String.toFloat pieceWidth)) }

view : Model -> Html Msg
view model =
  div
    [ Html.Attributes.style "margin" "1rem 2vw"
    , Html.Attributes.style "font-size" "2rem" ]
    [ label [] [ Html.text "Width" ]
    , input [ Html.Attributes.style "font-size" "1.7rem", Html.Attributes.type_ "number", Html.Attributes.step "0.1", Html.Attributes.placeholder "Width", Html.Attributes.value (String.fromFloat model.width), Html.Events.onInput SetWidth ] []
    , drawPiece model
    ]

drawPiece : Model -> Html Msg
drawPiece model =
  let
    camera = Camera3d.perspective
      { viewpoint =
        Viewpoint3d.lookAt
          { focalPoint = Point3d.meters 2 0 0
          , eyePoint = Point3d.meters 5 2 25
          , upDirection = Direction3d.y
          }
      , verticalFieldOfView = Angle.degrees 30
      }
  in
  Scene3d.custom
    { camera = camera
    , lights = Scene3d.oneLight (Scene3d.Light.overhead
        { upDirection = Direction3d.y
        , chromaticity = Scene3d.Light.skylight
        , intensity = Illuminance.lux 20000
        })
    , exposure = Scene3d.exposureValue 10
    , toneMapping = Scene3d.reinhardToneMapping 5
    , whiteBalance = Scene3d.Light.daylight
    , antialiasing = Scene3d.multisampling
    , dimensions = ( Pixels.int 1024, Pixels.int 720 )
    , background = Scene3d.transparentBackground
    , clipDepth = Length.meters 10
    , entities = (drawFaces model.width model.segments)
    }

segmentToVector : Direction3d coordinates -> Segment -> Vector3d Length.Meters coordinates
segmentToVector baseDirection segment =
  let
    direction = Direction3d.rotateAround Axis3d.z (Angle.degrees (-1 * (Basics.toFloat segment.angle))) baseDirection
  in
  Vector3d.withLength (Length.meters segment.length) direction

segmentsToVectors : Direction3d coordinates -> Segment -> Array Segment -> Array (Vector3d Length.Meters coordinates)
segmentsToVectors baseDirection thisSegment segments =
  let
    nextSegment = Array.get 0 segments
    nextSegments = Array.sliceFrom 1 segments
    thisVector = (segmentToVector (Direction3d.reverse baseDirection) thisSegment)
    curDirection = Vector3d.direction thisVector
  in
  case nextSegment of
    Just segment ->
      case curDirection of
        Just direction -> Array.append (Array.fromList [thisVector]) (segmentsToVectors direction segment nextSegments)
        Nothing -> Array.append  (Array.fromList [thisVector]) (segmentsToVectors baseDirection segment nextSegments)
    Nothing ->
      Array.fromList [thisVector]


segmentVectorsToLines : Point3d Length.Meters coordinates -> Vector3d Length.Meters coordinates -> Array (Vector3d Length.Meters coordinates) -> Array (LineSegment3d Length.Meters coordinates)
segmentVectorsToLines origin thisSegment segmentVectors =
  let
    thisLine = LineSegment3d.fromPointAndVector origin thisSegment
    nextSegment = Array.get 0 segmentVectors
  in
  case nextSegment of
    Just segmentVector ->
      let
        remainingSegments = (Array.sliceFrom 1 segmentVectors)
      in
      Array.append (Array.fromList [thisLine]) (segmentVectorsToLines (LineSegment3d.endPoint thisLine) segmentVector remainingSegments)
    Nothing ->
      Array.fromList [thisLine]

segmentsToLines : Array Segment -> Array (LineSegment3d Length.Meters coordinates)
segmentsToLines segments =
  let
    origin = (Point3d.origin)
    baseDirection = Direction3d.y
    firstSegment = Array.get 0 segments
    nextSegments = Array.sliceFrom 1 segments
  in
  case firstSegment of
    Just segment ->
      let
        segmentVectors = (segmentsToVectors baseDirection segment nextSegments)
        firstSegmentVector = Array.get 0 segmentVectors
        nextSegmentVectors = Array.sliceFrom 1 segmentVectors
      in
      case firstSegmentVector of
        Just segmentVector -> segmentVectorsToLines origin segmentVector nextSegmentVectors
        Nothing -> Array.fromList []
    Nothing -> Array.fromList []

drawFace : Float -> LineSegment3d Length.Meters coordinates -> Scene3d.Entity coordinates
drawFace pieceWidth segmentProfileLine =
  let
    segmentBackgroundLine = LineSegment3d.translateBy (Vector3d.withLength (Length.meters pieceWidth) (Direction3d.negativeZ)) segmentProfileLine
  in
  (Scene3d.quad
    (Scene3d.Material.matte (Color.fromRgba {red=(12/255), green=(54/255), blue=(55/255), alpha=0.5 }))
    (LineSegment3d.endPoint segmentProfileLine)
    (LineSegment3d.endPoint segmentBackgroundLine)
    (LineSegment3d.startPoint segmentBackgroundLine)
    (LineSegment3d.startPoint segmentProfileLine))

drawFaces : Float -> Array Segment -> List (Scene3d.Entity coordinates)

drawFaces pieceWidth segments =
  let
    segmentLines = (segmentsToLines segments)
    segmentFaces = (Array.map (drawFace pieceWidth) segmentLines)
  in
  (Array.toList segmentFaces)
```

The key here is that I'm tring to draw a sequence of folds done on plastic, usually the person draws the profile by hand on a piece of paper, be it n-shaped as the one I defined above or whatever, then draws some diagonal lines to give some sense of perspective. I was hoping to automate this process by using only the fold angles and segment lengths, which are defined by the person. Many problems arose including trying to draw the quads in counter-clockwise order (I did test out a ridiculous number of `if`s and variants and stuff, but it didn't solve this problem so I put it aside for now). I have many other alternatives I'm looking at such as drawing only a wireframe version and stuff, but solving transparency would be pretty nice.

**Comment by w0rm** [comment]
@frnco thanks for sharing the code, I will look into this. My example is actually a part of this PR, I made a change to  `examples/ExposureAndToneMapping.elm` and  `testing/TestApp.elm`.

**Comment by frnco** [comment]
@w0rm thanks, I'll also take a look at your example. For now I've added a toggle that switches the rendering order like this:

```Elm
if model.invertFaces then
    (Scene3d.quadWithShadow
      material
      (LineSegment3d.endPoint segmentProfileLine)
      (LineSegment3d.endPoint segmentBackgroundLine)
      (LineSegment3d.startPoint segmentBackgroundLine)
      (LineSegment3d.startPoint segmentProfileLine))
  else
    (Scene3d.quadWithShadow
      material
      (LineSegment3d.startPoint segmentProfileLine)
      (LineSegment3d.startPoint segmentBackgroundLine)
      (LineSegment3d.endPoint segmentBackgroundLine)
      (LineSegment3d.endPoint segmentProfileLine))
```

This way as far as I've seen all quads will have at least one side that is transparent. If I try to use both methods concurrently for different quads, everything becomes opaque, which led me to believe there's something else going on, possibly joining the quads in a single object and wreaking havoc somehow. Thanks for taking a look at this.

Either way, this is already pretty great, and the toggle makes things quite easier already, so I think @ianmackenzie should put reviewing this on the top of the priorities for this project.

**Comment by ianmackenzie** [comment]
@frnco I assure you I realize that transparency is an important feature, I have already been working/pairing with @w0rm on this PR, and the plan is certainly to have the transparency functionality fully documented by the time it is released 🙂 That said, I also have several other open-source (and personal) projects on the go and I may not always be able to jump on specific PRs/feature requests immediately.

In your case would it be feasible to manually order the quads to be in the correct back-to-front order? It should be possible via a flag/option to support either the current behavior (everything is fully automatic, but you'll only ever see the nearest front face and nearest back face, which in the case of quads means only one face since there are no back faces) or a modified behavior where you can get nearest-front and nearest-back _per object_ but where correct ordering of objects is left up to the user. Does that make sense?

**Comment by frnco** [comment]
> That said, I also have several other open-source (and personal) projects on the go and I may not always be able to jump on specific PRs/feature requests immediately.

i did notice that, I was actually very surprised by the number of Elm Packages managed by you, it was already surprising to see mdgriffith dealing with half a dozen packages, but you have 16 elm packages listed, I can't even imagine  how much work that must be. I wouldn't be even close to where I am today if not for your Geometry package.

That said, I believe transparency and edge highlighting (i.e. wireframing) are among the top priorities, if not THE top priorities, for the rendering-side of things. Now one of the biggest challenges I've been facing while working with Elm is the code structure, how to organize files, functions etc., and I do have over a decade of experience coding professionally to help me with that, but either because I did too little Functional programming or because of some quirks that might be specific to elm, it's taking me quite longer than usual to wrap my head around the libraries. On that note, I believe it might be a good idea for you to add either documentation or some references to where documentation and code for such things can be found, and some general information on how things work. I will continue studying how this actually works and try to come up with solutions for problems I notice, but some pointers could help speed things up, and I imagine there may be others who are also having trouble when trying to make sense of the code, especially relating to design decisions that may be deeply tied to Elm itself or to the functional programming paradigm.

Well it's just a suggestion, as the one who's most knowledgeable about the project you're the best one to decide whether it's worth expanding the documentation and how that should be done.

**Pull request merged**
