### PR TITLE
Demo for testing lights and materials

### LINKED ISSUE #38: Create demo scenes for material/light picking
Would be useful to have a few representative scenes (standalone web apps) with a shape in the middle that has customizable material, roughness etc., and be able to tweak the scene lighting; should provide a nice way to quickly find reasonable material/lighting values

### PR DESCRIPTION
**Pull request by w0rm**
Closes #38

elm-3d-scene

1. ~~This code breaks elm-format :(~~
2. Logarithmic scale is probably needed for some parameters 
3. The furniture and floor are not configurable, maybe we should give them realistic colors 
4. ~~The background is not changing, what should it be — just a color picker?~~
5. Bulbs do not change their color depending on the temperature
6. Bulbs cannot be moved at the moment
6. The styling of Html could be better, but I wanted to keep it simple

### CODE REVIEW

**Comment by ianmackenzie** [comment]
Looking good! I agree that the furniture and floor should ideally have realistic colors - one of my hopes for this demo is that it looks realistic enough that people can accurately figure out good lighting values by just looking at the scene and asking themselves if it "looks natural". For background, I think transparent is probably fine.

A few notes:

- Roughness sliders don't seem to do anything
- It's not immediately obvious that 'Rendering options', 'Objects' etc. can be clicked to expand their sections
- The values for several sliders are displayed with a distracting number of decimal places; I'd say either just round to the nearest integer or perhaps use https://package.elm-lang.org/packages/myrho/elm-round/latest/ for customizable formatting
- Maybe add "K" to the displayed temperature values, e.g. "5600 K"?
- I think we'll want to be able to control exposure as well; likely use `Exposure.fromEv100` and have a range of 5 to 16 labelled as "EV"
- "intensity", not "intencity"; "metal", not "metall" =)

**Comment by w0rm** [comment]
@ianmackenzie I addressed your notes, let me know if there is anything else that we can improve for MVP

**Comment by ianmackenzie** [comment]
This is looking good! I'm thinking of merging it in as is and then playing around with a few things. I might try to add something like https://cc0textures.com/view?tex=Wood34 to the table, for example - I kind of like the idea that a chunk of the scene (tables and chairs) should be as realistic as possible (not configurable) so that lighting values can be assessed easily, and then the sphere/cylinder/block on the table can be used for experimenting with all sorts of crazy materials.

Do you have strong opinions on having the UI on the left vs. right side? I think I personally prefer the left, so it's in order input -> output...

**Comment by w0rm** [comment]
I don't have any strong opinion about the layout. Feel free to rearrange things to your preference!

**Pull request merged**
